---
Name: application
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - AppSiteConfig
SilverStripe\Blog\Model\Blog:
  extensions:
    - SilverStripe\Widgets\Extensions\WidgetPageExtension
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - SilverStripe\Widgets\Extensions\WidgetPageExtension
